---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: immich
resources:
  - namespace.yaml
  - database.yaml
  - storage.yaml
  - immich.yaml
configMapGenerator:
  - name: immich-values
    namespace: immich
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true