apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: mqtt
    app.kubernetes.io/name: mosquitto
    app.kubernetes.io/version: 2.0.14
  name: mqtt-mosquitto
spec:
  ports:
  - name: mqtt
    port: 1883
    protocol: TCP
    targetPort: mqtt
  selector:
    app.kubernetes.io/instance: mqtt
    app.kubernetes.io/name: mosquitto
  sessionAffinity: None
  type: ClusterIP
