---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - barman-plugin.yaml
  - operator.yaml
configMapGenerator:
  - name: cnpg-values
    namespace: cloudnative-pg
    files:
      - values.yaml
generatorOptions:
  disableNameSuffixHash: true