apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: datentraum-base
resources:
  - ../../base/networking/dns-manager
patches:
  - target:
      kind: OnePasswordItem
      name: hetzner-credentials
      namespace: external-dns
    patch: |-
      - op: replace
        path: /spec/itemPath
        value: "vaults/VS-Infra/items/hetzner-api-key"
  # - target:
  #     kind: HelmRelease
  #     name: grafana
  #     namespace: monitoring
  #   patch: |-
  #     - op: add
  #       path: /spec/values
  #       value: 
  #         grafana:
  #           ingress:
  #             hosts:        
  #               - "grafana.vanille.hamburg"
  #           persistence:
  #             enabled: true
  #             storageClassName: hcloud-volumes
  #         prometheus:
  #           prometheusSpec:
  #             storageSpec:
  #               volumeClaimTemplate:
  #                 spec:
  #                   storageClassName: hcloud-volumes