---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - database.yaml
# configMapGenerator:
#   - name: immich-values
#     namespace: immich
#     files:
#       - values.yaml
# generatorOptions:
#   disableNameSuffixHash: true