apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base
resources:
  - security
  - operator
  - monitoring
  - networking/dns-manager
#  - storage/manual-pv
#  - storage/nfs-provisioner