apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: base
resources:
  - operator
#  - monitoring
  - security
  - networking/dns-manager
  - storage/manual-pv
  - cluster_pg

